name: dockerhub

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push - estuary-main
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:estuary-main"
          push: true
          tags: zorlin/estuary-main:latest
      - name: Build and push - estuary-shuttle
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:estuary-shuttle"
          push: true
          tags: zorlin/estuary-shuttle:latest
      - name: Build and push - estuary-www
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:estuary-www"
          push: true
          tags: zorlin/estuary-www:latest